target-version = "py310"
line-length = 120

# https://beta.ruff.rs/docs/rules/
select = ["ALL"]

ignore = [
    "ANN002",
    "ANN003",
    "ANN101",
]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".envs",
    ".git",
    "**/tests/**",
    "**/migrations/*",
]

[flake8-quotes]
inline-quotes = "single"
